### ISSUE TITLE
Dashboard Version 2

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/Covid19CanadaDashboard#41]
This issue will serve as a hub for planning version 2 of the dashboard, which will use our new [`CovidTimelineCanada`](https://github.com/ccodwg/CovidTimelineCanada) dataset and focus on a smaller number of more meaningful metrics as we navigate the third year of the COVID-19 pandemic.

Below is a rough outline of what we expect the dashboard to look like (single page):

1. Wastewater trends
  - Highlight most reliable source of population-wide prevalence data
  - Get people comfortable with reading and interpreting the infectious disease surveillance mechanism of the future
2. What is going on near you?
  - Detailed data for individual provinces/health regions, with data to contextualize & text to help interpretation
3. Vaccination coverage
  - Province-level vaccination coverage map/trends
4. Comparisons between provinces/health regions
5. Customizable visualizations
  - Provide more options for customized visualizations/comparisons/tables (for power users)

Before development can begin, we must first address the following issues:

- [x] Update `data_updater.R` to use `CovidTimelineCanada` (#45)
- [ ] Add wastewater data to `CovidTimelineCanada` (ccodwg/CovidTimelineCanada#36)

As an additional note, it would be nice to work with a plotting framework that translates well to a simple HTML/JS page in case we lose access to a paid `shinyapps.io` account and need to transfer to a GitHub Pages-based deployment. [ApexCharts.js](https://apexcharts.com/) is nice and is supported by the `htmlwidgets` library [`apexcharter`](https://github.com/dreamRs/apexcharter).

**Comment by jeanpaulrsoucy** [comment]
Add the COVID Data Discussions page from COVID-19 Resources Canada as another thought-provoking resource: https://covid19resources.ca/data-discussions

**Comment by jeanpaulrsoucy** [comment]
Another idea for a plot could be republishing PHAC's [variant data](https://health-infobase.canada.ca/covid-19/#VOC) (maybe with some supplemental data acquired from various provincial data sources or even one of the large, collaborative sequence banks) combined with a table with links to learn more about emerging variants. Could have a drop-down menu for displaying federal data versus data from other places that report ([Quebec](https://www.inspq.qc.ca/covid-19/donnees/variants), at minimum).

**Comment by kbelisar** [comment]
## Tasks to Still Complete:

### Aesthetics

**Essential**

- [ ] Address mortality data faceted plot y-axis going below 0 (apexcharter::ax_yaxis() arguments not working)
- [ ] Add either an About tab, or add an "about" description underneath the title (see UI wastewater shiny::tags$body("", align = "center") to add this)

**Desirable**

- [ ] Y-axis title for each facet
- [ ] X-axis text more detailed than just ~6months
- [ ] Menu bar permanently at the top
- [ ] Toggling of regions so that not all are on the plot at once
- [ ] Different mortality colour-scheme (greys?)

### Data

**Priority**

- [ ] Additional wastewater if possible from other sources
- [ ] Hospitalizations by HR
- [ ] Mortality by HR
- [ ] Hospitalizations - discriminate by ICU and regular Hospital admissions
- [ ] Vaccination rates (booster + bivalent)

**Future features**

- [ ] Home page map of Canada with HRs providing overview of trends from past week (hover over increase, decrease etc.)
